version: '3.7'

services:
  # proxy:
  #   image: nginx:alpine
  #   container_name: proxy
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
      - '8080:8000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
  postgres:
    image: postgres
    restart: always
    container_name: swcorp_postgres 
    networks:
      - backend
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'

  authenticator:
    build: ./authenticator
    image: swcorp/authenticator
    container_name: swcorp_authenticator
    networks: 
      - backend
    ports:
      - '8000:8000'

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
